Support for medic and ammo resupplier abilities on Combine soldiers
entropy-zero/source-sdk-2013 pull request #233
Opened 2023-11-22 07:53 UTC by Blixibon

Allows specific Combine soldiers to act as medics or ammo resuppliers when specified by the mapper. This behavior was ported from citizens and functions identically to them.

This is in draft status due to two questions about the implementation:

1. Every medic/ammo resupplier-related cvar is currently a distinct copy of an identical cvar used by citizens. The alternative would be to externally draw from the original citizen cvars, which may be simpler and more efficient, but would provide less control over any potential tweaks to soldier medics without also changing citizen medics.
2. Soldiers currently use two new spawnflags for respectively becoming a medic or an ammo resupplier in the same way citizens have spawnflags, although they do not use the same bits. New spawnflags can be an issue if there's a chance forks of E:Z2 have custom spawnflags for soldiers, but this is unlikely.

@1upD I'm curious to hear if you have any input on these points

2024-01-13 09:19 UTC, GitHubUser53123 commented
dang

2024-02-25 21:46 UTC, 1upD commented on sp/src/game/server/hl2/npc_combine.cpp
> +				DevMsg("ERROR: Citizen attempting to give unknown ammo type (%s)\n", STRING(m_iszAmmoSupply) );
This should probably say "Combine", "Combine soldier", or "soldier". Maybe even insert the classname

2024-02-25 21:53 UTC, 1upD commented
I feel very conflicted about how heavily this code copies from existing code in the citizen class. Citizens, vortigaunts, and now Combine soldiers need to heal. Maybe some day Metrocops will need to as well. I feel like there should be some way to share this feature between different NPCs, like perhaps making it part of the PlayerCompanion class or separating it into its own behavior. However, I also think that those approaches would risk changing the original functionality, which would not be desired. I think for that reason this is probably the best way to do it even if it is a little copy and paste heavy. It just makes me wish NPCs were more modular.

I also want to state that Combine soldiers not healing in EZ2 was a design choice and I think that was good for the overall narrative of the game. For those watching this PR, just for complete clarity, this functionality is for use in custom maps or future content. It's not something that will be seen in the main game.

2024-02-25 21:55 UTC, 1upD commented
As far as the questions go:

1. Separate ConVars is ideal so that Combine healing values can be tweaked separately from citizens.
2. I think the concern about spawnflags is valid. Especially because these spawnflags wouldn't have parity with the Citizen spawn flags. I'd prefer to use a key value just in case.

2024-03-06 22:28 UTC, 1upD requested changes

2024-03-06 22:28 UTC, 1upD commented on sp/src/game/server/hl2/npc_combine.h
> +#define SF_COMBINE_MEDIC ( 1 << 22 ) // Citizen-like medic
Unless you change your mind, I think we want to make this a key value so we're not worried about the order of spawnflags or if another spawnflag could come from Mapbase and collide or something along those lines

2024-07-14 15:19 UTC, Yankumo-Koishi commented
How's going about this? Haven't seen any activities in the months

2024-08-25 18:23 UTC, 1upD commented
@Blixibon Do we need this PR to be merged for testing in the near future? It looks like it's still in draft status with unaddressed comments. No pressure if we don't need it, I just want to make sure it's not forgotten.

2025-01-31 19:09 UTC, Blixibon commented
I've addressed the concern regarding the spawnflags and force-pushed this branch to the latest version of `ez2/mapbase` in case of build automation errors.

2025-08-19 01:10 UTC, 1upD commented on sp/src/game/server/hl2/npc_combine.cpp
> +			DevMsg( "Would say: sorry, need to recharge\n" );
Nitpick, but this should have the debug name of the NPC

2025-08-19 01:12 UTC, 1upD commented on sp/src/game/server/hl2/npc_combine.cpp
> +	TossHealthKit( UTIL_GetLocalPlayer(), Vector(48.0f, 0.0f, 0.0f)  );
It would be cool if we could use the input to specify another entity by targetname, but I digress

2025-08-19 01:16 UTC, 1upD commented
This PR is ancient but I'm thinking of merging it before the next release. Maybe another smaller release before 2.0

2025-09-01 03:34 UTC, 1upD commented on sp/src/game/server/hl2/npc_combine.cpp
> +ConVar	sk_combine_heal_ally_min_pct( "sk_combine_heal_ally_min_pct", "0.90" );
It looks like this and the following ConVars are unused

2025-09-01 19:36 UTC, 1upD approved these changes

2025-11-11 05:23 UTC, merged